### ISSUE TITLE
Provider 'fund to apply to' shows no funds message

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#513] opened 2018-12-10 20:50 UTC
- [ ] counter is 0, should be 2 (based on amount of funds)
- [ ] No active funds apply to message is visible, should not be the case with two funds to apply to.

![image](https://user-images.githubusercontent.com/10818702/49760247-3ce17c00-fcc4-11e8-9cbc-f837736e9380.png)

**Comment by GerbenBosschieter** [comment] 2018-12-21 08:16
can't reproduce this. Maybe @dev-rminds fixed it. Didn't see a commit about this. Will close this for now, pleas reopen if someone sees it again.

**Closed by GerbenBosschieter** 2018-12-21 08:16 UTC
Labels: bug
