### ISSUE TITLE
Add the "authorise device" functionality to every front-end for every role.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#518] opened 2018-12-11 12:37 UTC
## Context/goal: 
At the sign-up flow it's currently possible to connect the Me-app with the profile they created by the authorisation code. I've already had support questions about the authorising device after they finished the sign up flow.  They can do this on the webshop. But it's a bit weird for the user experience and on a certain implementation the webshop isn't released yet.

## Request
Add the "authorise device" functionality to every front-end for every role. It's currently only possible for people who use the webshop.

**Comment by maxvisser** [comment] 2018-12-11 12:39
duplicate of https://github.com/teamforus/forus/issues/292

**Closed by maxvisser** 2018-12-11 12:39 UTC
Labels: enhancement
