### ISSUE TITLE
Simplify / clarify email fields

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#365] opened 2018-11-14 18:57 UTC
Currently with on boarding we ask for the email address 3 times; once for the user, then for the organisation and then for the office. We should improve communication on this and clarify why we do this. (can example add an (i) button). We should also mark things as optional if they are optional.

**Comment by maxvisser** [comment] 2018-11-14 19:07
https://github.com/teamforus/forus/issues/365

**Comment by maxvisser** [comment] 2018-11-14 19:07
duplicate of #349

**Closed by maxvisser** 2018-11-14 19:07 UTC
