### ISSUE TITLE
Signup-v2 Redirect to the dashboard does not work

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1630] opened 2020-07-03 09:04 UTC
Should be fixed from release/v0.12.2

## Description
Sign-up v2: After applying I am not getting redirected to the dashboar

**URL tested:** https://staging.forus.io/provider/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.forus.io%2Fprovider%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.forus.io/provider/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1732x910 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/f51fed8aaeba1f76ad363466f3ea194191a40429/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/f51fed8aaeba1f76ad363466f3ea194191a40429/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.forus.io%2Fprovider%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.forus.io/provider/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment] 2020-07-03 09:05
Duplicate of https://github.com/teamforus/forus/issues/1599

**Comment by maxvisser** [comment] 2020-07-03 09:07
Closed the other one; as this one is more clear to that it is related to IE

**Comment by maxvisser** [comment] 2020-07-03 09:07
Can you still manually open the dashboard?

**Comment by GerbenBosschieter** [comment] 2020-07-03 09:18
Yes and also refreshing will redirect you

**Comment by GerbenBosschieter** [comment] 2020-07-03 09:23
@maxvisser It's not only related to IE. Same issue on Chrome

**Comment by GerbenBosschieter** [comment] 2020-07-03 09:24
@maxvisser Note: opening dashbaord doesn't work either! this wil redirect. you to the landing page and not dashboard. But refreshing after this, does work.

**Comment by maxvisser** [comment] 2020-07-03 09:26
Ah I also saw this but didn't think anything of it and just refreshed.

**Comment by GerbenBosschieter** [comment] 2020-07-03 09:41
@maxvisser bad Max, bad Max!

**Closed** 2020-07-06 05:51 UTC
Labels: Difficulty: Medium, Priority: Must have, Scope: Small
