### ISSUE TITLE
Kindpakket page: alignment issue

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#889] opened 2019-05-23 19:21 UTC
See lower left:

<img width="1232" alt="Screenshot 2019-05-23 at 21 20 20" src="https://user-images.githubusercontent.com/30194799/58280322-a059f480-7da0-11e9-944e-0354f0e5fef4.png">

**Comment by maxvisser** [comment] 2019-05-25 18:51
duplicate of #895

**Closed by maxvisser** 2019-05-25 18:51 UTC
Labels: website
