### ISSUE TITLE
Popup - You applied for the fund.

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#322] opened 2018-11-08 22:47 UTC
We need a pupup to display after the provider applied for the fund stating some information like:

- You request is recieved
- Please wait for the municipality to accept your request
- Average waiting time is x days
- etc.

@GerbenBosschieter I will need text we can show there, and after please reassign me, so I can give it to be designed to Alex.

**Comment by maxvisser** [comment] 2018-11-09 07:29
Duplicate of https://github.com/teamforus/forus/issues/315

**Closed** 2018-11-09 07:36 UTC
Labels: UX / UI
