### ISSUE TITLE
Email adres taken after installing me app and trying to activate code.

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#170] opened 2018-10-15 13:58 UTC
When I already have an account before trying the activation code while not being logged in, I get email adres taken. This is not the behaviour that I expect as a user, I think I should be allowed to sign in with my email adres in this flow > using email adres / using qr code in the me app.

<img width="1205" alt="screenshot 2018-10-15 at 15 44 46" src="https://user-images.githubusercontent.com/30194799/46954641-6b125900-d091-11e8-8e98-f63c95b0d23a.png">

**Comment by GerbenBosschieter** [comment] 2018-10-15 16:38
Yes we've talked about this. I think this issue needs to be discussed for a proper solution. I was thinking about improvement of the communication to the user, but you were talking about the functionality itself.

I assign @maxvisser @danrminds @GerbenBosschieter @jamalv so we can think of a proper solution before we ask @dev-rminds to solve this.

**Comment by maxvisser** [comment] 2018-10-15 18:48
in jamals proposal he makes the assumption that the user has a Me app. It could also be that the user first activated his account via Kindpakket and after that via a new fund. While not downloading the me app at all.

Also the activation code doesnt generate a voucher code but resembles prevalidated attributes, therefor its much more scalable to remove the whole activation code button from the webshop all together and only allow activation codes in the me app. 

I see three stages in fixing this issue
1. A quick fix for this issue is improvement of communication to the user.

2. Improvement on user friendlies would be to add a login functionality if the email address is valid (login via mail of me app screen)

3. As the me app and forus will have seperate backends in, you can't add prevalidated records any more without user interaction. The user should be able to authorize the platform to add records to the Me app.

**Comment by GerbenBosschieter** [comment] 2018-10-19 07:48
Let's go for the communication for now

**Comment by maxvisser** [comment] 2018-10-20 16:43
I see that you fixed by changing:
"Vul je e-mail adres en activatiecode in om verder te gaan met aanmelden" 
to
"Dit scherm is alleen bedoeld voor inwoners die een brief van de gemeente hebben ontvangen met daarin een activatiecode en deze nog niet hebben gebruikt."

Is this to your satisfaction @jamalv

**Comment by jamalv** [comment] 2018-10-20 18:08
@maxvisser Option 1 really feels like a workaround. I can still imagine it causing confusion and a poor user experience. I like option 2 much more, since it prevents re-routing the user if they have an account and forcing them to re-enter the activation code. I think the original text: "Vul je e-mail adres en activatiecode in om verder te gaan met aanmelden" is good and simple.

Since this is an edge case, I think communication with the user should be in the error message:

_"It seems like you already have an account, please [sign in]() before filling in your activation code."_

Still, option 2 is much better in my eyes :)

**Comment by GerbenBosschieter** [comment] 2018-10-21 16:21
Yes but the problem is, that the error message for an code being used is the as someone using an invalid code.

**Comment by jamalv** [comment] 2018-10-21 16:33
I think that this error should be used if email is already taken (user already created an account, for example in me app) that should be another error, right?

**Closed** 2018-10-23 14:23 UTC
Labels: UX / UI
