### ISSUE TITLE
Connection between records repository and service

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#43] opened 2018-05-28 07:43 UTC
Establish connection between docker containers of the records repository and IPFS records service

**Comment by maxvisser** [comment] 2018-05-31 13:44
I think this issue is a duplicate of https://github.com/teamforus/forus.io/issues/43

**Comment by jamalv** [comment] 2018-06-03 12:33
@maxvisser, this is issue #43 :)

**Comment by maxvisser** [comment] 2018-06-03 16:30
I meant #12

**Comment by danrminds** [comment] 2018-06-04 09:28
Yes, both issues mean at most the same thing. This is more specific though as it refers to a specific repository and specific service, skipping other parts that are stated in #12

**Comment by jamalv** [comment] 2018-06-07 06:12
The purpose of a hello world is to show that all parts of the system work together in a very elementary form, this is just about two parts of the system. I think the hello world should be the main priority, now that we have a couple different services, and also already native apps. Closing this issue in favor of #12. We can update that issue to make it more concrete and continue the disscussion there.

**Closed** 2018-08-24 11:29 UTC
