### ISSUE TITLE
IE: Token expired or unknown after backspacing multiple times on input fields

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1348] opened 2020-01-06 09:20 UTC
IF a user backspaces multiple times while a input field is open, it will give an error.

IT looks like this problem only occurs on IE

**URL tested:** https://staging.berkelland.forus.io/confirmation/email/51f6989b0136e68e95bf82fb9e043c74557e0c2ef9d24498e8d9ce568f527037c9078d4835bfdf89900494c916506397bd11d4785317fe4f362b9dcb836d425e3bad96fbdd86be99c9ab7c4802940b05378c7e2a013685adf52deeb01a0ec7f591b10a8b?target=

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.berkelland.forus.io%2Fconfirmation%2Femail%2F51f6989b0136e68e95bf82fb9e043c74557e0c2ef9d24498e8d9ce568f527037c9078d4835bfdf89900494c916506397bd11d4785317fe4f362b9dcb836d425e3bad96fbdd86be99c9ab7c4802940b05378c7e2a013685adf52deeb01a0ec7f591b10a8b%3Ftarget%3D&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.berkelland.forus.io/confirmation/email/51f6989b0136e68e95bf82fb9e043c74557e0c2ef9d24498e8d9ce568f527037c9078d4835bfdf89900494c916506397bd11d4785317fe4f362b9dcb836d425e3bad96fbdd86be99c9ab7c4802940b05378c7e2a013685adf52deeb01a0ec7f591b10a8b?target=&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1416x1000 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/00489e712320f69d74fef33c6bb0e306ac130000/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/00489e712320f69d74fef33c6bb0e306ac130000/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.berkelland.forus.io%2Fconfirmation%2Femail%2F51f6989b0136e68e95bf82fb9e043c74557e0c2ef9d24498e8d9ce568f527037c9078d4835bfdf89900494c916506397bd11d4785317fe4f362b9dcb836d425e3bad96fbdd86be99c9ab7c4802940b05378c7e2a013685adf52deeb01a0ec7f591b10a8b%3Ftarget%3D&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://staging.berkelland.forus.io/confirmation/email/51f6989b0136e68e95bf82fb9e043c74557e0c2ef9d24498e8d9ce568f527037c9078d4835bfdf89900494c916506397bd11d4785317fe4f362b9dcb836d425e3bad96fbdd86be99c9ab7c4802940b05378c7e2a013685adf52deeb01a0ec7f591b10a8b?target=&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment] 2020-02-06 11:20
lets test this again on new release 0.9.0

**Comment by maxvisser** [comment] 2020-04-24 09:37
@SjoerdHilhorst could to check if this is still an issue?

**Comment by SjoerdHilhorst** [comment] 2020-04-28 10:08
all our websites except general gives a white screen so i am not even able to test this

example:

open [berkelland.staging.forus.io](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.berkelland.forus.io%2Fconfirmation%2Femail%2F51f6989b0136e68e95bf82fb9e043c74557e0c2ef9d24498e8d9ce568f527037c9078d4835bfdf89900494c916506397bd11d4785317fe4f362b9dcb836d425e3bad96fbdd86be99c9ab7c4802940b05378c7e2a013685adf52deeb01a0ec7f591b10a8b%3Ftarget%3D&speed=1&host_ports=google.com%2C80%2C0) on browserstack

**Comment by maxvisser** [comment] 2020-04-28 11:26
Sorry; Backend was not correctly deployed; should be fixed now

**Comment by SjoerdHilhorst** [comment] 2020-05-04 08:13
tried multiple input fields, can't reproduce it.

**Closed by SjoerdHilhorst** 2020-05-04 08:13 UTC
Labels: Difficulty: Medium, Priority: Could have, Scope: Small
