### ISSUE TITLE
Make help.forus.io generic

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#952] opened 2019-07-12 09:34 UTC
For future implementations and when adding new features it would be very practical to be able to refer to help.forus.io. In order to be able to do this it needs to be generic.

Example: The implementation of the new voucher functionality #214. To be able to implement this successfully users need to be able to learn about its workings. This could be explained using help.forus.io.

- Remove logo of municipality
- Change texts by removing references to specific "regelingen"

@maxvisser @GerbenBosschieter @linda-90 What would be necessary to be able to do this?

This issue can be closed when help.forus.io is generic and has been added to the dashboards as explained in #854 .

**Comment by maxvisser** [comment] 2019-07-12 11:19
I think this is a duplicate of an internal issue: https://github.com/teamforus/projects/issues/34
If there are any conclusion there of waht needs to be developed issues about code can be added here. even #854

**Closed by maxvisser** 2019-07-12 11:19 UTC
