### ISSUE TITLE
Prevent different height of product blocks

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#715] opened 2019-01-18 14:15 UTC
## Context/goal: 
<img width="1253" alt="screen shot 2019-01-18 at 15 13 31" src="https://user-images.githubusercontent.com/38419514/51391945-caba4d80-1b33-11e9-9dbe-b106e811aeb0.png">

**Comment by maxvisser** [comment] 2019-01-20 09:42
Duplicate of https://github.com/teamforus/forus/issues/656

**Closed by maxvisser** 2019-01-20 09:42 UTC
Labels: UX / UI, frontend
