### ISSUE TITLE
Signup v2: fixes

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1566] opened 2020-05-28 14:14 UTC
## Context/goal: 
Some team members noticed we didn't use the new sing up form yet.
Just got a call of on our clients who also asked about the signupflow and is going to start a campagne nest week to onboard 200 providers. He would like to have the signup flow ready for mobile.

And the new one has a mobile version :)

## Task
It's clear that we want to switch ASAP to the new signupform.
So we need to create issues to decide what is needed to switch to the new form.
There are already some issues. But we need to test and create more issues. 

- https://github.com/teamforus/forus/issues/1561
- https://github.com/teamforus/forus/issues/1560
- https://github.com/teamforus/forus/issues/1555

**Comment by GerbenBosschieter** [comment] 2020-05-28 14:20
https://staging.forus.io/provider/sign-up-v2

**Comment by GerbenBosschieter** [comment] 2020-05-28 14:22
@linda-90 you had some new text right. And there where some typo's in the current version.
Could you link your figma link ?

**Comment by GerbenBosschieter** [comment] 2020-05-28 14:24
Assigned all of you guys, everybody with an opinion ;)

**Comment by linda-90** [comment] 2020-05-28 14:27
@GerbenBosschieter https://www.figma.com/file/WUqFTERVi1FRn44LyspS8E/%F0%9F%8C%8DForus?node-id=1743%3A100177

**Comment by maartenfv** [comment] 2020-05-28 14:33
@GerbenBosschieter Jamal was 1 minute faster with this issue: https://github.com/teamforus/general/issues/221

**Comment by jamalv** [comment] 2020-05-28 14:54
This figma link is leading from now: https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/Signupflow-v2-texts?node-id=0%3A1

**Comment by maxvisser** [comment] 2020-06-09 12:28
I will close this one as it is a duplicate of the IP in general repo. Lets move the discussion there guys!
https://github.com/teamforus/general/issues/221

**Closed by maxvisser** 2020-06-09 12:28 UTC
Labels: Difficulty: Easy, Priority: Should have, Scope: Medium
