### ISSUE TITLE
Add links when mentioning Me and download options

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#723] opened 2019-01-21 08:58 UTC
![image](https://user-images.githubusercontent.com/30211022/51462794-d428fd00-1d61-11e9-9abd-51f258abeacc.png)

As in the image above links need to be added in the text.

**Comment by maxvisser** [comment] 2019-01-21 14:54
I like these additions but the user flow of sending people to play store / app store is horrible as they can't really download the app on desktop

**Comment by GerbenBosschieter** [comment] 2019-01-21 16:14
I think maarten means a link to the me-landingspage.
But don't you guys think its a little bit to much to make every reference to the me app clickable .

**Comment by jamalv** [comment] 2019-01-21 17:42
Yea, I think to a landing page. There we could explain (/show) how the user will be able to download the me app once they have a voucher (using the sms function). That's probably the best ux / way to create awareness.

Maybe not every link has to be clickable, but in every location where the user might see the term "me-app" for the first time it would be good.

**Comment by jamalv** [comment] 2019-01-24 09:35
@maartenfv duplicate of https://github.com/teamforus/forus/issues/718 ?

**Comment by maartenfv** [comment] 2019-02-21 15:07
@jamalv The conclusion makes it a duplicate. I like linking to a information page on Me when the concept is first mentioned.

**Closed** 2019-03-15 07:34 UTC
Labels: UX / UI, frontend
