### ISSUE TITLE
Sign-up v2: Bussines hours input bug

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1591] opened 2020-06-08 11:34 UTC
IT looks like you can't save any offices anymore after you have choose to set up bussines hours and later deselect this. Gives an error about formatting.

**URL tested:** https://dev.forus.io/provider/#!/sign-up-v2

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.forus.io%2Fprovider%2F%23!%2Fsign-up-v2&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.forus.io/provider/#!/sign-up-v2&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1904x1000 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/731f3c6819322b4f29a14653b0ad28536a547c9d/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/731f3c6819322b4f29a14653b0ad28536a547c9d/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.forus.io%2Fprovider%2F%23!%2Fsign-up-v2&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.forus.io/provider/#!/sign-up-v2&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by maxvisser** [comment] 2020-06-09 12:36
could be a duplicate of the other bug we have which stops user from creating an office.

**Closed** 2020-06-29 08:56 UTC
Labels: bug
